// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBve29ipSexmATCosL6oDcM8uz414tPbv0',
    appId: '1:943067865641:web:e72bfb6874d9a89b3c3238',
    messagingSenderId: '943067865641',
    projectId: 'inver-sync',
    authDomain: 'inver-sync.firebaseapp.com',
    storageBucket: 'inver-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOUFmpZCAuZByzHKrvLfk8i_JFAlhdOY',
    appId: '1:943067865641:android:9e734931030df02f3c3238',
    messagingSenderId: '943067865641',
    projectId: 'inver-sync',
    storageBucket: 'inver-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4T24DTX5_9yGJDtf_0bjYFhFmhf6Umlo',
    appId: '1:943067865641:ios:f744c74ca748ec3c3c3238',
    messagingSenderId: '943067865641',
    projectId: 'inver-sync',
    storageBucket: 'inver-sync.firebasestorage.app',
    iosBundleId: 'com.example.inverSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4T24DTX5_9yGJDtf_0bjYFhFmhf6Umlo',
    appId: '1:943067865641:ios:f744c74ca748ec3c3c3238',
    messagingSenderId: '943067865641',
    projectId: 'inver-sync',
    storageBucket: 'inver-sync.firebasestorage.app',
    iosBundleId: 'com.example.inverSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBve29ipSexmATCosL6oDcM8uz414tPbv0',
    appId: '1:943067865641:web:d7e85ab596a762413c3238',
    messagingSenderId: '943067865641',
    projectId: 'inver-sync',
    authDomain: 'inver-sync.firebaseapp.com',
    storageBucket: 'inver-sync.firebasestorage.app',
  );
}
